apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init-dbs.sql: |
    CREATE DATABASE IF NOT EXISTS catalog_db;
    CREATE DATABASE IF NOT EXISTS order_db;
    CREATE DATABASE IF NOT EXISTS rating_db;
    CREATE DATABASE IF NOT EXISTS notification_db;
